#!/usr/bin/env bash

set -euo pipefail

work_dir="$(dirname "${BASH_SOURCE[0]}")"
echo "Executing podman build in '${work_dir}' directory:"
cd "${work_dir}"

exec podman build \
  --build-arg "USER_NAME=$(id --user --name)" \
  --build-arg "USER_ID=$(id --user)" \
  --build-arg "GROUP_NAME=$(id --group --name)" \
  --build-arg "GROUP_ID=$(id --group)" \
  --build-arg "HOME=${HOME}" \
  --build-arg "VIBE_HOME=${VIBE_HOME:-${HOME}/.vibe}" \
  --tag vibe-sandbox \
  .
